// Built-in word categories for Word Scramble.
// Each category: { id, name, words }
// Each word entry: { word, difficulty: 'easy'|'medium'|'hard' }
// Words are plain A-Z only, single words (no spaces/punctuation) — see
// spec.md Non-goals on multi-word phrases. Scrambling happens at deck-build
// time in js/game.js, not here — this file is content only.

export const CATEGORIES = [
  {
    id: 'animals',
    name: 'Animals',
    words: [
      // easy
      { word: 'LION', difficulty: 'easy' },
      { word: 'TIGER', difficulty: 'easy' },
      { word: 'ZEBRA', difficulty: 'easy' },
      { word: 'SHARK', difficulty: 'easy' },
      { word: 'EAGLE', difficulty: 'easy' },
      { word: 'OTTER', difficulty: 'easy' },
      { word: 'HORSE', difficulty: 'easy' },
      { word: 'GOAT', difficulty: 'easy' },
      { word: 'FROG', difficulty: 'easy' },
      { word: 'MOUSE', difficulty: 'easy' },
      { word: 'SNAKE', difficulty: 'easy' },
      { word: 'SHEEP', difficulty: 'easy' },
      { word: 'HAWK', difficulty: 'easy' },
      { word: 'SWAN', difficulty: 'easy' },
      { word: 'CRAB', difficulty: 'easy' },
      { word: 'DUCK', difficulty: 'easy' },
      { word: 'WOLF', difficulty: 'easy' },
      // medium
      { word: 'RABBIT', difficulty: 'medium' },
      { word: 'MONKEY', difficulty: 'medium' },
      { word: 'DOLPHIN', difficulty: 'medium' },
      { word: 'PANTHER', difficulty: 'medium' },
      { word: 'PENGUIN', difficulty: 'medium' },
      { word: 'GIRAFFE', difficulty: 'medium' },
      { word: 'BADGER', difficulty: 'medium' },
      { word: 'JAGUAR', difficulty: 'medium' },
      { word: 'LOBSTER', difficulty: 'medium' },
      { word: 'OSTRICH', difficulty: 'medium' },
      { word: 'RACCOON', difficulty: 'medium' },
      { word: 'SQUIRREL', difficulty: 'medium' },
      { word: 'CHEETAH', difficulty: 'medium' },
      { word: 'LEOPARD', difficulty: 'medium' },
      { word: 'MEERKAT', difficulty: 'medium' },
      { word: 'PELICAN', difficulty: 'medium' },
      { word: 'VULTURE', difficulty: 'medium' },
      // hard
      { word: 'ELEPHANT', difficulty: 'hard' },
      { word: 'CROCODILE', difficulty: 'hard' },
      { word: 'KANGAROO', difficulty: 'hard' },
      { word: 'ORANGUTAN', difficulty: 'hard' },
      { word: 'CHIMPANZEE', difficulty: 'hard' },
      { word: 'ARMADILLO', difficulty: 'hard' },
      { word: 'HIPPOPOTAMUS', difficulty: 'hard' },
      { word: 'RHINOCEROS', difficulty: 'hard' },
      { word: 'PORCUPINE', difficulty: 'hard' },
      { word: 'HEDGEHOG', difficulty: 'hard' },
      { word: 'ALLIGATOR', difficulty: 'hard' },
      { word: 'FLAMINGO', difficulty: 'hard' },
      { word: 'ANTELOPE', difficulty: 'hard' },
      { word: 'BUTTERFLY', difficulty: 'hard' },
      { word: 'CATERPILLAR', difficulty: 'hard' },
      { word: 'HUMMINGBIRD', difficulty: 'hard' },
    ],
  },
  {
    id: 'food-and-drinks',
    name: 'Food & Drinks',
    words: [
      // easy
      { word: 'PIZZA', difficulty: 'easy' },
      { word: 'BREAD', difficulty: 'easy' },
      { word: 'APPLE', difficulty: 'easy' },
      { word: 'GRAPE', difficulty: 'easy' },
      { word: 'HONEY', difficulty: 'easy' },
      { word: 'LEMON', difficulty: 'easy' },
      { word: 'PASTA', difficulty: 'easy' },
      { word: 'MANGO', difficulty: 'easy' },
      { word: 'PEACH', difficulty: 'easy' },
      { word: 'SALAD', difficulty: 'easy' },
      { word: 'BACON', difficulty: 'easy' },
      { word: 'CHERRY', difficulty: 'easy' },
      { word: 'ONION', difficulty: 'easy' },
      { word: 'SUSHI', difficulty: 'easy' },
      { word: 'TOAST', difficulty: 'easy' },
      { word: 'WAFFLE', difficulty: 'easy' },
      { word: 'YOGURT', difficulty: 'easy' },
      // medium
      { word: 'BURGER', difficulty: 'medium' },
      { word: 'COFFEE', difficulty: 'medium' },
      { word: 'NOODLE', difficulty: 'medium' },
      { word: 'CARROT', difficulty: 'medium' },
      { word: 'BANANA', difficulty: 'medium' },
      { word: 'PANCAKE', difficulty: 'medium' },
      { word: 'AVOCADO', difficulty: 'medium' },
      { word: 'POPCORN', difficulty: 'medium' },
      { word: 'OMELET', difficulty: 'medium' },
      { word: 'BISCUIT', difficulty: 'medium' },
      { word: 'PRETZEL', difficulty: 'medium' },
      { word: 'SMOOTHIE', difficulty: 'medium' },
      { word: 'TORTILLA', difficulty: 'medium' },
      { word: 'CUPCAKE', difficulty: 'medium' },
      { word: 'LASAGNA', difficulty: 'medium' },
      { word: 'MEATBALL', difficulty: 'medium' },
      { word: 'DUMPLING', difficulty: 'medium' },
      // hard
      { word: 'SANDWICH', difficulty: 'hard' },
      { word: 'SPAGHETTI', difficulty: 'hard' },
      { word: 'CHOCOLATE', difficulty: 'hard' },
      { word: 'CASSEROLE', difficulty: 'hard' },
      { word: 'BLUEBERRY', difficulty: 'hard' },
      { word: 'QUESADILLA', difficulty: 'hard' },
      { word: 'ENCHILADA', difficulty: 'hard' },
      { word: 'CROISSANT', difficulty: 'hard' },
      { word: 'MOZZARELLA', difficulty: 'hard' },
      { word: 'PEPPERONI', difficulty: 'hard' },
      { word: 'CAULIFLOWER', difficulty: 'hard' },
      { word: 'WATERMELON', difficulty: 'hard' },
      { word: 'STRAWBERRY', difficulty: 'hard' },
      { word: 'MACARONI', difficulty: 'hard' },
      { word: 'GUACAMOLE', difficulty: 'hard' },
      { word: 'MARSHMALLOW', difficulty: 'hard' },
    ],
  },
  {
    id: 'movies-and-shows',
    name: 'Movies & Shows',
    words: [
      // easy
      { word: 'SHREK', difficulty: 'easy' },
      { word: 'JOKER', difficulty: 'easy' },
      { word: 'MOANA', difficulty: 'easy' },
      { word: 'ALIEN', difficulty: 'easy' },
      { word: 'JAWS', difficulty: 'easy' },
      { word: 'ROCKY', difficulty: 'easy' },
      { word: 'BAMBI', difficulty: 'easy' },
      { word: 'CARS', difficulty: 'easy' },
      { word: 'BRAVE', difficulty: 'easy' },
      { word: 'COCO', difficulty: 'easy' },
      { word: 'MULAN', difficulty: 'easy' },
      { word: 'ANNIE', difficulty: 'easy' },
      { word: 'RANGO', difficulty: 'easy' },
      { word: 'TAKEN', difficulty: 'easy' },
      { word: 'GHOST', difficulty: 'easy' },
      { word: 'TWISTER', difficulty: 'easy' },
      { word: 'SPEED', difficulty: 'easy' },
      // medium
      { word: 'FROZEN', difficulty: 'medium' },
      { word: 'MATRIX', difficulty: 'medium' },
      { word: 'AVATAR', difficulty: 'medium' },
      { word: 'GREASE', difficulty: 'medium' },
      { word: 'TITANIC', difficulty: 'medium' },
      { word: 'JUMANJI', difficulty: 'medium' },
      { word: 'ENCANTO', difficulty: 'medium' },
      { word: 'WICKED', difficulty: 'medium' },
      { word: 'CHICAGO', difficulty: 'medium' },
      { word: 'GOONIES', difficulty: 'medium' },
      { word: 'PSYCHO', difficulty: 'medium' },
      { word: 'ALADDIN', difficulty: 'medium' },
      { word: 'TARZAN', difficulty: 'medium' },
      { word: 'CASINO', difficulty: 'medium' },
      { word: 'SCREAM', difficulty: 'medium' },
      { word: 'TANGLED', difficulty: 'medium' },
      { word: 'ONWARD', difficulty: 'medium' },
      // hard
      { word: 'ZOOTOPIA', difficulty: 'hard' },
      { word: 'INCEPTION', difficulty: 'hard' },
      { word: 'GLADIATOR', difficulty: 'hard' },
      { word: 'RATATOUILLE', difficulty: 'hard' },
      { word: 'INTERSTELLAR', difficulty: 'hard' },
      { word: 'ANNABELLE', difficulty: 'hard' },
      { word: 'GOODFELLAS', difficulty: 'hard' },
      { word: 'CASABLANCA', difficulty: 'hard' },
      { word: 'BRAVEHEART', difficulty: 'hard' },
      { word: 'TERMINATOR', difficulty: 'hard' },
      { word: 'GHOSTBUSTERS', difficulty: 'hard' },
      { word: 'JURASSIC', difficulty: 'hard' },
      { word: 'DEADPOOL', difficulty: 'hard' },
      { word: 'MOONLIGHT', difficulty: 'hard' },
      { word: 'WHIPLASH', difficulty: 'hard' },
      { word: 'SLUMDOG', difficulty: 'hard' },
    ],
  },
  {
    id: 'everyday-objects',
    name: 'Everyday Objects',
    words: [
      // easy
      { word: 'CHAIR', difficulty: 'easy' },
      { word: 'TABLE', difficulty: 'easy' },
      { word: 'PHONE', difficulty: 'easy' },
      { word: 'BRUSH', difficulty: 'easy' },
      { word: 'CLOCK', difficulty: 'easy' },
      { word: 'LAMP', difficulty: 'easy' },
      { word: 'SPOON', difficulty: 'easy' },
      { word: 'KNIFE', difficulty: 'easy' },
      { word: 'FORK', difficulty: 'easy' },
      { word: 'PLATE', difficulty: 'easy' },
      { word: 'TOWEL', difficulty: 'easy' },
      { word: 'GLOVE', difficulty: 'easy' },
      { word: 'STOOL', difficulty: 'easy' },
      { word: 'BROOM', difficulty: 'easy' },
      { word: 'HANGER', difficulty: 'easy' },
      { word: 'WHISK', difficulty: 'easy' },
      { word: 'LADLE', difficulty: 'easy' },
      // medium
      { word: 'PENCIL', difficulty: 'medium' },
      { word: 'MIRROR', difficulty: 'medium' },
      { word: 'BLANKET', difficulty: 'medium' },
      { word: 'WALLET', difficulty: 'medium' },
      { word: 'CAMERA', difficulty: 'medium' },
      { word: 'BUCKET', difficulty: 'medium' },
      { word: 'CANDLE', difficulty: 'medium' },
      { word: 'PILLOW', difficulty: 'medium' },
      { word: 'LADDER', difficulty: 'medium' },
      { word: 'BOTTLE', difficulty: 'medium' },
      { word: 'BASKET', difficulty: 'medium' },
      { word: 'STAPLER', difficulty: 'medium' },
      { word: 'SPATULA', difficulty: 'medium' },
      { word: 'BLENDER', difficulty: 'medium' },
      { word: 'TOASTER', difficulty: 'medium' },
      { word: 'CHARGER', difficulty: 'medium' },
      { word: 'HAMMER', difficulty: 'medium' },
      // hard
      { word: 'BACKPACK', difficulty: 'hard' },
      { word: 'UMBRELLA', difficulty: 'hard' },
      { word: 'KEYBOARD', difficulty: 'hard' },
      { word: 'TOOTHBRUSH', difficulty: 'hard' },
      { word: 'REFRIGERATOR', difficulty: 'hard' },
      { word: 'SCISSORS', difficulty: 'hard' },
      { word: 'CALENDAR', difficulty: 'hard' },
      { word: 'NOTEBOOK', difficulty: 'hard' },
      { word: 'TELEVISION', difficulty: 'hard' },
      { word: 'MICROWAVE', difficulty: 'hard' },
      { word: 'HEADPHONES', difficulty: 'hard' },
      { word: 'SCREWDRIVER', difficulty: 'hard' },
      { word: 'THERMOMETER', difficulty: 'hard' },
      { word: 'FLASHLIGHT', difficulty: 'hard' },
      { word: 'SUITCASE', difficulty: 'hard' },
      { word: 'WHEELBARROW', difficulty: 'hard' },
    ],
  },
  {
    id: 'sports-and-games',
    name: 'Sports & Games',
    words: [
      // easy
      { word: 'GOLF', difficulty: 'easy' },
      { word: 'DARTS', difficulty: 'easy' },
      { word: 'CHESS', difficulty: 'easy' },
      { word: 'RUGBY', difficulty: 'easy' },
      { word: 'BOXING', difficulty: 'easy' },
      { word: 'SOCCER', difficulty: 'easy' },
      { word: 'HOCKEY', difficulty: 'easy' },
      { word: 'TENNIS', difficulty: 'easy' },
      { word: 'SKIING', difficulty: 'easy' },
      { word: 'DIVING', difficulty: 'easy' },
      { word: 'ROWING', difficulty: 'easy' },
      { word: 'KARATE', difficulty: 'easy' },
      { word: 'JUDO', difficulty: 'easy' },
      { word: 'POLO', difficulty: 'easy' },
      { word: 'RELAY', difficulty: 'easy' },
      { word: 'RACING', difficulty: 'easy' },
      { word: 'CANOE', difficulty: 'easy' },
      // medium
      { word: 'CRICKET', difficulty: 'medium' },
      { word: 'SURFING', difficulty: 'medium' },
      { word: 'CYCLING', difficulty: 'medium' },
      { word: 'FENCING', difficulty: 'medium' },
      { word: 'ARCHERY', difficulty: 'medium' },
      { word: 'BOWLING', difficulty: 'medium' },
      { word: 'CURLING', difficulty: 'medium' },
      { word: 'SOFTBALL', difficulty: 'medium' },
      { word: 'FOOTBALL', difficulty: 'medium' },
      { word: 'BASEBALL', difficulty: 'medium' },
      { word: 'LACROSSE', difficulty: 'medium' },
      { word: 'HANDBALL', difficulty: 'medium' },
      { word: 'PADDLING', difficulty: 'medium' },
      { word: 'CLIMBING', difficulty: 'medium' },
      { word: 'SPRINTING', difficulty: 'medium' },
      { word: 'SKATING', difficulty: 'medium' },
      { word: 'WRESTLING', difficulty: 'medium' },
      // hard
      { word: 'SNOWBOARD', difficulty: 'hard' },
      { word: 'TRIATHLON', difficulty: 'hard' },
      { word: 'PICKLEBALL', difficulty: 'hard' },
      { word: 'VOLLEYBALL', difficulty: 'hard' },
      { word: 'GYMNASTICS', difficulty: 'hard' },
      { word: 'BADMINTON', difficulty: 'hard' },
      { word: 'SKATEBOARD', difficulty: 'hard' },
      { word: 'WEIGHTLIFTING', difficulty: 'hard' },
      { word: 'PENTATHLON', difficulty: 'hard' },
      { word: 'DECATHLON', difficulty: 'hard' },
      { word: 'MARATHON', difficulty: 'hard' },
      { word: 'POWERLIFTING', difficulty: 'hard' },
      { word: 'RACQUETBALL', difficulty: 'hard' },
      { word: 'WATERPOLO', difficulty: 'hard' },
      { word: 'PARAGLIDING', difficulty: 'hard' },
      { word: 'MOTOCROSS', difficulty: 'hard' },
    ],
  },
  {
    id: 'jobs-and-people',
    name: 'Jobs & People',
    words: [
      // easy
      { word: 'CHEF', difficulty: 'easy' },
      { word: 'NURSE', difficulty: 'easy' },
      { word: 'PILOT', difficulty: 'easy' },
      { word: 'JUDGE', difficulty: 'easy' },
      { word: 'ACTOR', difficulty: 'easy' },
      { word: 'MAYOR', difficulty: 'easy' },
      { word: 'COACH', difficulty: 'easy' },
      { word: 'MODEL', difficulty: 'easy' },
      { word: 'GUARD', difficulty: 'easy' },
      { word: 'CLERK', difficulty: 'easy' },
      { word: 'MAID', difficulty: 'easy' },
      { word: 'BAKER', difficulty: 'easy' },
      { word: 'FARMER', difficulty: 'easy' },
      { word: 'TAILOR', difficulty: 'easy' },
      { word: 'BUTLER', difficulty: 'easy' },
      { word: 'BARBER', difficulty: 'easy' },
      { word: 'DOCTOR', difficulty: 'easy' },
      // medium
      { word: 'DENTIST', difficulty: 'medium' },
      { word: 'LAWYER', difficulty: 'medium' },
      { word: 'TEACHER', difficulty: 'medium' },
      { word: 'PLUMBER', difficulty: 'medium' },
      { word: 'BUILDER', difficulty: 'medium' },
      { word: 'SURGEON', difficulty: 'medium' },
      { word: 'SOLDIER', difficulty: 'medium' },
      { word: 'PAINTER', difficulty: 'medium' },
      { word: 'DRUMMER', difficulty: 'medium' },
      { word: 'SCIENTIST', difficulty: 'medium' },
      { word: 'ENGINEER', difficulty: 'medium' },
      { word: 'ASTRONAUT', difficulty: 'medium' },
      { word: 'MUSICIAN', difficulty: 'medium' },
      { word: 'MECHANIC', difficulty: 'medium' },
      { word: 'CARPENTER', difficulty: 'medium' },
      { word: 'BUTCHER', difficulty: 'medium' },
      { word: 'SINGER', difficulty: 'medium' },
      // hard
      { word: 'ELECTRICIAN', difficulty: 'hard' },
      { word: 'ACCOUNTANT', difficulty: 'hard' },
      { word: 'PLAYWRIGHT', difficulty: 'hard' },
      { word: 'JOURNALIST', difficulty: 'hard' },
      { word: 'PHOTOGRAPHER', difficulty: 'hard' },
      { word: 'FIREFIGHTER', difficulty: 'hard' },
      { word: 'VETERINARIAN', difficulty: 'hard' },
      { word: 'PSYCHOLOGIST', difficulty: 'hard' },
      { word: 'CHOREOGRAPHER', difficulty: 'hard' },
      { word: 'ARCHAEOLOGIST', difficulty: 'hard' },
      { word: 'PALEONTOLOGIST', difficulty: 'hard' },
      { word: 'ILLUSTRATOR', difficulty: 'hard' },
      { word: 'CINEMATOGRAPHER', difficulty: 'hard' },
      { word: 'UPHOLSTERER', difficulty: 'hard' },
      { word: 'LEXICOGRAPHER', difficulty: 'hard' },
      { word: 'ANESTHESIOLOGIST', difficulty: 'hard' },
    ],
  },
  {
    id: 'actions',
    name: 'Actions',
    words: [
      // easy
      { word: 'JUMP', difficulty: 'easy' },
      { word: 'RUN', difficulty: 'easy' },
      { word: 'WALK', difficulty: 'easy' },
      { word: 'SWIM', difficulty: 'easy' },
      { word: 'DANCE', difficulty: 'easy' },
      { word: 'SLEEP', difficulty: 'easy' },
      { word: 'LAUGH', difficulty: 'easy' },
      { word: 'SHOUT', difficulty: 'easy' },
      { word: 'CLIMB', difficulty: 'easy' },
      { word: 'THROW', difficulty: 'easy' },
      { word: 'CATCH', difficulty: 'easy' },
      { word: 'PUSH', difficulty: 'easy' },
      { word: 'PULL', difficulty: 'easy' },
      { word: 'CRAWL', difficulty: 'easy' },
      { word: 'SKIP', difficulty: 'easy' },
      { word: 'SPIN', difficulty: 'easy' },
      { word: 'KICK', difficulty: 'easy' },
      // medium
      { word: 'WHISPER', difficulty: 'medium' },
      { word: 'STUMBLE', difficulty: 'medium' },
      { word: 'WRESTLE', difficulty: 'medium' },
      { word: 'JUGGLE', difficulty: 'medium' },
      { word: 'SPRINT', difficulty: 'medium' },
      { word: 'TUMBLE', difficulty: 'medium' },
      { word: 'SQUEEZE', difficulty: 'medium' },
      { word: 'STRETCH', difficulty: 'medium' },
      { word: 'SHIVER', difficulty: 'medium' },
      { word: 'WOBBLE', difficulty: 'medium' },
      { word: 'SCATTER', difficulty: 'medium' },
      { word: 'SCRAMBLE', difficulty: 'medium' },
      { word: 'BALANCE', difficulty: 'medium' },
      { word: 'WHISTLE', difficulty: 'medium' },
      { word: 'SNEEZE', difficulty: 'medium' },
      { word: 'GALLOP', difficulty: 'medium' },
      { word: 'POUNCE', difficulty: 'medium' },
      // hard
      { word: 'SOMERSAULT', difficulty: 'hard' },
      { word: 'CARTWHEEL', difficulty: 'hard' },
      { word: 'HANDSTAND', difficulty: 'hard' },
      { word: 'PIROUETTE', difficulty: 'hard' },
      { word: 'CELEBRATE', difficulty: 'hard' },
      { word: 'INVESTIGATE', difficulty: 'hard' },
      { word: 'CONGRATULATE', difficulty: 'hard' },
      { word: 'HIBERNATE', difficulty: 'hard' },
      { word: 'IMPROVISE', difficulty: 'hard' },
      { word: 'CONCENTRATE', difficulty: 'hard' },
      { word: 'DEMONSTRATE', difficulty: 'hard' },
      { word: 'EXAGGERATE', difficulty: 'hard' },
      { word: 'INTERROGATE', difficulty: 'hard' },
      { word: 'CAMOUFLAGE', difficulty: 'hard' },
      { word: 'ORGANIZE', difficulty: 'hard' },
      { word: 'MULTIPLY', difficulty: 'hard' },
    ],
  },
  {
    id: 'places',
    name: 'Places',
    words: [
      // easy
      { word: 'PARK', difficulty: 'easy' },
      { word: 'BEACH', difficulty: 'easy' },
      { word: 'SCHOOL', difficulty: 'easy' },
      { word: 'CHURCH', difficulty: 'easy' },
      { word: 'MARKET', difficulty: 'easy' },
      { word: 'KITCHEN', difficulty: 'easy' },
      { word: 'GARAGE', difficulty: 'easy' },
      { word: 'BRIDGE', difficulty: 'easy' },
      { word: 'TUNNEL', difficulty: 'easy' },
      { word: 'ISLAND', difficulty: 'easy' },
      { word: 'DESERT', difficulty: 'easy' },
      { word: 'FOREST', difficulty: 'easy' },
      { word: 'CASTLE', difficulty: 'easy' },
      { word: 'HARBOR', difficulty: 'easy' },
      { word: 'VALLEY', difficulty: 'easy' },
      { word: 'JUNGLE', difficulty: 'easy' },
      { word: 'CANYON', difficulty: 'easy' },
      // medium
      { word: 'STADIUM', difficulty: 'medium' },
      { word: 'AIRPORT', difficulty: 'medium' },
      { word: 'MUSEUM', difficulty: 'medium' },
      { word: 'HOSPITAL', difficulty: 'medium' },
      { word: 'BAKERY', difficulty: 'medium' },
      { word: 'FACTORY', difficulty: 'medium' },
      { word: 'MOUNTAIN', difficulty: 'medium' },
      { word: 'VOLCANO', difficulty: 'medium' },
      { word: 'GLACIER', difficulty: 'medium' },
      { word: 'APARTMENT', difficulty: 'medium' },
      { word: 'BASEMENT', difficulty: 'medium' },
      { word: 'STAIRCASE', difficulty: 'medium' },
      { word: 'WAREHOUSE', difficulty: 'medium' },
      { word: 'COURTYARD', difficulty: 'medium' },
      { word: 'LIBRARY', difficulty: 'medium' },
      { word: 'CAFETERIA', difficulty: 'medium' },
      { word: 'STATION', difficulty: 'medium' },
      // hard
      { word: 'CATHEDRAL', difficulty: 'hard' },
      { word: 'PLAYGROUND', difficulty: 'hard' },
      { word: 'CAMPGROUND', difficulty: 'hard' },
      { word: 'LIGHTHOUSE', difficulty: 'hard' },
      { word: 'RESTAURANT', difficulty: 'hard' },
      { word: 'UNIVERSITY', difficulty: 'hard' },
      { word: 'LABORATORY', difficulty: 'hard' },
      { word: 'OBSERVATORY', difficulty: 'hard' },
      { word: 'PLANETARIUM', difficulty: 'hard' },
      { word: 'GREENHOUSE', difficulty: 'hard' },
      { word: 'SKYSCRAPER', difficulty: 'hard' },
      { word: 'COURTHOUSE', difficulty: 'hard' },
      { word: 'MONASTERY', difficulty: 'hard' },
      { word: 'AQUARIUM', difficulty: 'hard' },
      { word: 'AMPHITHEATER', difficulty: 'hard' },
      { word: 'COLOSSEUM', difficulty: 'hard' },
    ],
  },
];
